# Generated by Django 5.1.3 on 2024-12-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.TextField(default="Texto padrão"),
            preserve_default=False,
        ),
    ]
